/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conversor_de_un_boton;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class Conversor_de_un_boton extends javax.swing.JFrame {

    /**
     * Creates new form Conversor_de_un_boton
     */
    public Conversor_de_un_boton() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        getContentPane().setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conversorLabel = new javax.swing.JLabel();
        centimetrosLabel = new javax.swing.JLabel();
        pulgadasLabel = new javax.swing.JLabel();
        centimetrosTextField = new javax.swing.JTextField();
        pulgadasTextField = new javax.swing.JTextField();
        convertirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de longitud");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        conversorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        conversorLabel.setText("CONVERSOR CENTÍMETROS-PULGADAS");

        centimetrosLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        centimetrosLabel.setText("Centímetros");

        pulgadasLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pulgadasLabel.setText("Pulgadas");

        centimetrosTextField.setBackground(new java.awt.Color(255, 204, 204));
        centimetrosTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                centimetrosTextFieldFocusGained(evt);
            }
        });
        centimetrosTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                centimetrosTextFieldKeyTyped(evt);
            }
        });

        pulgadasTextField.setBackground(new java.awt.Color(255, 204, 204));
        pulgadasTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pulgadasTextFieldFocusGained(evt);
            }
        });
        pulgadasTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pulgadasTextFieldKeyTyped(evt);
            }
        });

        convertirButton.setBackground(new java.awt.Color(102, 255, 153));
        convertirButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        convertirButton.setText("Convertir");
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conversorLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(centimetrosLabel)
                            .addComponent(pulgadasLabel))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pulgadasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(centimetrosTextField))
                        .addGap(36, 36, 36)
                        .addComponent(convertirButton)
                        .addGap(14, 14, 14)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(conversorLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(centimetrosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centimetrosLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pulgadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulgadasLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(convertirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        // TODO add your handling code here:
        bandera=1;
        String centimetrosString=centimetrosTextField.getText();
        if(!centimetrosString.isEmpty())
            centimetrosTextFieldFocusGained(null);
        else
        {
            String pulgadasString;
            pulgadasString = pulgadasTextField.getText();
            if(!pulgadasString.isEmpty())
                pulgadasTextFieldFocusGained(null);
            else
            {
                JOptionPane.showMessageDialog(this,"\n Ambas celdas están vacías \n No hay nada que convertir","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                bandera=0;
            } 
        }
            
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void centimetrosTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_centimetrosTextFieldFocusGained
        // TODO add your handling code here:
        pulgadasTextField.setText("");
        if(bandera==1)
        {
            String centimetrosString=centimetrosTextField.getText();
            double centimetros=Double.valueOf(centimetrosString);
            double pulgadas=centimetros/2.54;
            String pulgadasString=String.format("%.2f",pulgadas);
            pulgadasString=pulgadasString.replace(',','.');
            pulgadasTextField.setText(pulgadasString);
            bandera=0;
        }
    }//GEN-LAST:event_centimetrosTextFieldFocusGained

    private void pulgadasTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pulgadasTextFieldFocusGained
        // TODO add your handling code here:      
        centimetrosTextField.setText("");
        if(bandera==1)
        {
        String pulgadasString=pulgadasTextField.getText();
        double pulgadas=Double.valueOf(pulgadasString);
        double centimetros=pulgadas*2.54;
        String centimetrosString=String.format("%.2f",centimetros);
        centimetrosString=centimetrosString.replace(',','.');
        centimetrosTextField.setText(centimetrosString);
        bandera=0;
        }
    }//GEN-LAST:event_pulgadasTextFieldFocusGained

    private void centimetrosTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_centimetrosTextFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c=='.')
        {
        String aux;
        aux=centimetrosTextField.getText();
        for(int i=0;i<aux.length();i++)
            if(aux.charAt(i)=='.')
                evt.consume();
        }
        if((c<'0'||c>'9')&&c!='.')
            evt.consume();
    }//GEN-LAST:event_centimetrosTextFieldKeyTyped

    private void pulgadasTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pulgadasTextFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c=='.')
        {
        String aux;
        aux=pulgadasTextField.getText();
        for(int i=0;i<aux.length();i++)
            if(aux.charAt(i)=='.')
                evt.consume();
        }
        if((c<'0'||c>'9')&&c!='.')
            evt.consume();
    }//GEN-LAST:event_pulgadasTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor_de_un_boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor_de_un_boton().setVisible(true);
            }
        });
    }

    int bandera=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel centimetrosLabel;
    private javax.swing.JTextField centimetrosTextField;
    private javax.swing.JLabel conversorLabel;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel pulgadasLabel;
    private javax.swing.JTextField pulgadasTextField;
    // End of variables declaration//GEN-END:variables
}
